### ISSUE TITLE
Import error in params.py

### ISSUE THREAD

**Issue by rathorevipul28** [Shivanshu-Gupta/in-context-learning#1]
When I am trying to run experiments.py to generate parameters for 8-shot ICL, I get following import error in params.py:
![Error](https://github.com/Shivanshu-Gupta/in-context-learning/assets/26379611/5586e578-570b-44ba-8946-f80974303959)

**Comment by Shivanshu-Gupta** [comment]
Hi Vipul, the error is because of the `list[str]` type annotation, which is only supported in Python 3.9 and later. I'd recommend using Python 3.10 for this code base.
