### ISSUE TITLE
Bug Report: converter.structure(d['selector'], sel2cls[d['selector']['selector_type']])

### ISSUE THREAD

**Issue by Zhaoyi-Li21** [Shivanshu-Gupta/in-context-learning#3]
Hi, Gupta.

I came across a bug when trying to run the codes.
I was running a testing shell file:
```
CUDA_VISIBLE_DEVICES=1 python experiments.py --label "test" --seeds 0 \
   --datasets "COGS" \
   --selectors "cosine" \
   --lms "llama2-7b" \
   --n-shots 8 --baselines-exp \
   --paramsfile "params/all.jsonl" --run \
   --no-collate-results \
   --preview "logfiles"

CUDA_VISIBLE_DEVICES=1 python run.py --paramsfile "params/all.jsonl" --gpus "1"
```
As you can see, it contains two python commands, where the first one `python experiments.py` succeeded while the second one `python run.py` failed.

the error location: "in-context-learning/src/params.py:123 in from_dict"
```
│   120 │   │   # DP = converter.structure(d['data'], DataParams)                                  │
│   121 │   │   DP = converter.structure(d['data'], ds2cls[d['data']['dataset']])                  │
│   122 │   │   LP = converter.structure(d['llm'], LLMParams)                                      │
│ ❱ 123 │   │   SP = converter.structure(d['selector'], sel2cls[d['selector']['selector_type']])   │
│   124 │   │   return cls(EP, DP, LP, SP)     
```
the error message: TypeError: CosineCoverageSelectorArgs.__init__() missing 1 required positional argument: 'n_shots'.

I tried to decompose the error so that anyone can reproduce the error with running the following minimal example code:

```
from selector import (
    CommonSelectorArgs,
    CosineCoverageSelectorArgs,
    BertScoreSelectorArgs,
    GistBertScoreSelectorArgs,
    StructuralCoverageSelectorArgs,
    LFCoverageSelectorArgs,
)

import attr    
import cattr

converter = cattr.Converter()
d = dict()

d = {                                                
'selector_type': 'cosine',      
'n_shots': 8,                                                                                                            
'emb_lm': 'sentence-transformers/all-mpnet-base-v2',                     
'coverage': False,                                                      
'reorder': False                                                              
}           
SP = converter.structure(d, CosineCoverageSelectorArgs) 
# Here we met up with the same ERROR!
# TypeError: CosineCoverageSelectorArgs.__init__() missing 1 required positional argument: 'n_shots'
print(SP)
```

To be more specific, `SP = converter.structure(d, CosineCoverageSelectorArgs) ` will assign the whole dictionary `d` as a string (maybe) to the first class variable of CosineCoverageSelectorArgs (which is `selector_type` in this case), but it makes no sense! Hence will be nothing to be assigned to the second class variable (`shot` here).

Do you have some thoughts about this bug?

Much appreciation for your time reading my question!

**Comment by Shivanshu-Gupta** [comment]
Hi, this happened because of some breaking changes in the latest versions of the [cattrs](https://github.com/python-attrs/cattrs) and/or [attrs](https://github.com/python-attrs/attrs) libraries. The simple fix should be to install version 23 of both: `mamba install attrs=23.2 cattrs=23.2`. I'll update the requirements.txt. I'm closing the issue, feel free to reopen if the issue persists.

**Comment by Zhaoyi-Li21** [comment]
It works. Gupta thanks for the response.
